force-app/main/default/objects/Item__c/Item__c.object-meta.xml
<CustomObject>
    <description>Object for ToDo app</description>
    <label>Item</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Item__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Today</fullName>
                <default>true</default>
                <label>Today</label>
            </value>
            <value>
                <fullName>Tomorrow</fullName>
            </value>
            <value>
                <fullName>Later</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Item__c/fields/IsDone__c.field-meta.xml
<CustomField>
    <fullName>IsDone__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsDone</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Normal</fullName>
                <default>true</default>
                <label>Normal</label>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ItemController.cls
public with sharing class ItemController {
    @AuraEnabled(Cacheable=true)
    public static List<Item__c> getItems() {
        return [
            SELECT Id, Name, Description__c, Creation_Date__c, Category__c, Priority__c, IsDone__c, Picture__c
            FROM Item__c
            ORDER BY Category__c
            LIMIT 50
        ];
    }

    @AuraEnabled(Cacheable=true)
    public static List<Item__c> searchItems(string searchKey) {
        return [
            SELECT Id, Name, Description__c, Creation_Date__c, Category__c, Priority__c, IsDone__c, Picture__c
            FROM Item__c
            WHERE Name LIKE : '%' + searchKey + '%'
            ORDER BY Category__c
        ];
    }
}